// The shape of data exchanged between the app and POST /api/sync.
// Timestamps are ms since epoch. All ids are UUIDs generated by whoever created
// the row, so the app can create decks and reviews while offline.

export interface SyncCard {
  id: string
  deckId: string
  front: string
  back: string
  ankiNoteId: string | null
  position: number | null // order new cards are shown in
}

export interface SyncDeck {
  id: string
  name: string
  description: string | null
}

export interface SyncDeckUpload extends SyncDeck {
  cards: Omit<SyncCard, 'deckId'>[]
}

export interface SyncReview {
  id: string
  cardId: string
  rating: number
  durationMs: number | null
  reviewedAt: number
}

export interface SyncProgress {
  cardId: string
  dueAt: number
  intervalDays: number
  ease: number
  reps: number
  lapses: number
  lastReviewedAt: number | null
}

export interface SyncExam {
  id: string
  deckId: string | null // null = all decks
  mode: 'choice' | 'self'
  minIntervalDays: number
  total: number
  correct: number
  answers: { cardId: string, correct: boolean }[]
  startedAt: number
  finishedAt: number
}

export interface SyncRequest {
  cursor: string | null // from the previous SyncResponse; null = send me everything
  decks: SyncDeckUpload[]
  reviews: SyncReview[]
  exams?: SyncExam[]
}

export interface SyncResponse {
  cursor: string
  rejectedReviewIds: string[] // e.g. card doesn't exist or isn't yours
  decks: SyncDeck[]
  cards: SyncCard[]
  progress: SyncProgress[]
  reviews: SyncReview[] // full history across devices, used for statistics
  exams: SyncExam[]
}
